codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: auto
        threshold: 1%

ignore:
  - "komorebi_client/lib/**/*.g.dart"
  - "komorebi_client/lib/**/*.freezed.dart"
  - "komorebi_client/lib/intl/generated/**/*"
  - "komorebi_client/test/**/*"
  - "komorebi_server/tests/**/*"

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
